app = "learn-datalog"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "8080"

[http_service]
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  size = "shared-cpu-1x"
  memory = "256MB"